.

diff --git a/data/scripts/certbot_create_prod_certs b/data/scripts/certbot_create_prod_certs
--- a/data/scripts/certbot_create_prod_certs
+++ b/data/scripts/certbot_create_prod_certs
@@ -31,7 +31,7 @@ if [[ "${CURRENT_ENV:-}" != "production" ]]; then
 fi
 
 
-[[ -z "${DOMAINS:-}" ]] && printf "\nERROR: Missing ENV DOMAINS. Check your .env file.\n\n" && exit 1
+[[ -z "${ALL_DOMAINS:-}" ]] && printf "\nERROR: Missing ENV ALL_DOMAINS. Check your .env file.\n\n" && exit 1
 
 certbot_cmd="certbot certonly"
 certbot_cmd="${certbot_cmd} --webroot -w /var/www/certbot"
@@ -39,7 +39,7 @@ certbot_cmd="${certbot_cmd} --email ${EMAIL} --noninteractive --agree-tos"
 certbot_cmd="${certbot_cmd} --force-renewal --expand --rsa-key-size 4096 "
 certbot_cmd="${certbot_cmd} --cert-name ${CURRENT_ENV}"
 
-for domain in $DOMAINS ; do
+for domain in $ALL_DOMAINS ; do
   certbot_cmd+=" -d ${domain}"
 done
 
diff --git a/data/scripts/create_nginx_conf b/data/scripts/create_nginx_conf
--- a/data/scripts/create_nginx_conf
+++ b/data/scripts/create_nginx_conf
@@ -13,12 +13,12 @@
 SCRIPTS_DIR=$(cd "$(dirname "$0")" || exit 1 && pwd)
 DATA_DIR="$(dirname "${SCRIPTS_DIR}")"
 
-[ -z "${DOMAINS:-}" ] && printf "\nERROR: Missing ENV DOMAINS. Check your .env file.\n\n" && exit 1
+[ -z "${ALL_DOMAINS:-}" ] && printf "\nERROR: Missing ENV ALL_DOMAINS. Check your .env file.\n\n" && exit 1
 [ -z "${CURRENT_ENV:-}" ] && printf "\nERROR: Missing ENV CURRENT_ENV. Check your .env file.\n\n" && exit 1
 [ -z "${MAIN_DOMAIN:-}" ] && printf "\nERROR: Missing ENV MAIN_DOMAIN. Check your .env file.\n\n" && exit 1
 
 if [ "${CURRENT_ENV}" != "production" ]; then
-  DOMAINS="_"
+  ALL_DOMAINS="_"
 fi
 
 _create_conf() {
@@ -38,8 +38,8 @@ _create_conf() {
   mkdir -p "$(dirname "$output_path")"
 
   # shellcheck disable=SC2016
-  DOMAINS=$DOMAINS CURRENT_ENV=$CURRENT_ENV MAIN_DOMAIN=$MAIN_DOMAIN \
-  envsubst '${DOMAINS} ${CURRENT_ENV} ${MAIN_DOMAIN}' \
+  ALL_DOMAINS=$ALL_DOMAINS CURRENT_ENV=$CURRENT_ENV MAIN_DOMAIN=$MAIN_DOMAIN \
+  envsubst '${ALL_DOMAINS} ${CURRENT_ENV} ${MAIN_DOMAIN}' \
   < "$template_path" \
   > "$output_path"
 }
